version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker  
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: integracao-pet-api
    ports: 
      - "3308:3306"
    networks: 
      - casa
  integracao-pet-api:
    image: integracao-pet-api
    restart: always
    build:
      context: .    
      dockerfile: Dockerfile
    working_dir: /
    environment: 
      TZ: America/Sao_Paulo
    ports: 
      - "8080:8081"  
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db 

networks:
    casa:
        driver: bridge
        