version: '3.4'
services:
  db:
    container_name: integracao-db
    image: mysql:5.7.22 
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker  
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: integracao-pet-api
    ports: 
      - 3308:3306
    networks: 
      - casa  
  integracao-pet-api:
    container_name: integracao-api
    image: integracao-pet-api
    restart: always
    build:
      context: .    
      dockerfile: Dockerfile
    working_dir: /
    environment: 
      TZ: America/Sao_Paulo
    ports: 
      - 8081:8080
    networks: 
      - casa    
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db 
networks:
    casa:
        driver: bridge
        